import pandas as pd
file_1 = pd.read_excel('Input_file.xlsx','Sheet1',index_col = None)
file_1.to_csv('Sheet1.csv')
file_2 = pd.read_excel('Input_file.xlsx','Sheet2',index_col = None)
file_2.to_csv('Sheet2.csv')
file_3 = pd.read_excel('Input_file.xlsx','Sheet3',index_col = None)
file_3.to_csv('Sheet3.csv')
file_4 = pd.read_excel('Input_file.xlsx','Sheet4',index_col = None)
file_4.to_csv('Sheet4.csv')
file_5 = pd.read_excel('Input_file.xlsx','Sheet5',index_col = None)
file_5.to_csv('Sheet5.csv')
file_6 = pd.read_excel('Input_file.xlsx','Sheet6',index_col = None)
file_6.to_csv('Sheet6.csv')
file_7 = pd.read_excel('Input_file.xlsx','Sheet7',index_col = None)
file_7.to_csv('Sheet7.csv')
file_8 = pd.read_excel('Input_file.xlsx','Sheet8',index_col = None)
file_8.to_csv('Sheet8.csv')
file_9 = pd.read_excel('Input_file.xlsx','Sheet9',index_col = None)
file_9.to_csv('Sheet9.csv')
file_10 = pd.read_excel('Input_file.xlsx','Sheet10',index_col = None)
file_10.to_csv('Sheet10.csv')
